import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

const fontFigtree = Figtree({
  weight: ['300','400','600','800'],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Fametonic: Your Fast Track to Going Viral",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontFigtree.className}`}>
      <body
        className={`${fontFigtree.className} bg-[#010101] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
